# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Ivan Napoli"
title_separator: "-"
name: "Ivan Napoli"
description: "Ivan Napoli, PhD Candidate in Economics of Innovation (Università Cattolica del Sacro Cuore of Milan)"
url: "https://ivannapo.github.io"
baseurl: ""               # vuoto se pubblichi alla radice
repository: "ivannapo/ivannapo.github.io"

# Author
author:
  avatar: "website2.jpeg"
  name: "Ivan Napoli"
  pronouns: "He/him"
  bio: "PhD candidate in Economics of Innovation"
  location: "Varese, Italy"
  email: "ivan.napoli@unicatt.it"
  linkedin: "ivan-napoli-0123"

# Publications categories (usa quelli che ti servono)
publication_category:
  books: { title: "Books" }
  manuscripts: { title: "Journal Articles" }
  conferences: { title: "Conference Papers" }

# Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: false                # ⚠️ disattiva contenuti datati nel futuro (no 2199)
read_more: "disabled"
talkmap_link: false

atom_feed:
  hide: false

# SEO (compila se li hai)
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username:
og_image:
og_description:
social:
  type: Person
  name: "Ivan Napoli"
  links: []

# Analytics (opzionale)
analytics:
  provider: "false"
  google:
    tracking_id:

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:                      # ⚠️ unica chiave exclude (non duplicarla)
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
  - _drafts
  - .jekyll-cache
  - .git
  - .gitignore
  - .github
  - CNAME

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections (solo quelle che usi davvero)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: true
  - scope: { path: "", type: teaching }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope: { path: "", type: publications }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope: { path: "", type: portfolio }
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope: { path: "", type: talks }
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Vienna

# Plugins (⚠️ unica chiave plugins – consolidate tutto qui)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag

# HTML Compression (ok mantenerlo semplice)
compress_html:
  clippings: all
  ignore:
    envs: development
